language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t ian90/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true ian90/react-test-app npm run test

after_success:
  - docker build -t ian90/docker-frontend ./frontend
  - docker build -t ian90/docker-backend ./backend
  - docker build -t ian90/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push ian90/docker-frontend
  - docker push ian90/docker-backend
  - docker push ian90/docker-nginx

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: EB에 생성된 어플리케이션의 이름
  env: EB에 생성된 환경이름
  bucket_name: 해당 elasticbeanstalk를 위한 s3 버켓 이름
  bucket_path: 어플리케이션 이름과 동일
  on:
    branch: master

access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_ACCESS_KEY
