FROM ubuntu:20.04
LABEL maintainer="lee"
# install apache
RUN apt-get update && apt-get install -y apache2
RUN echo "TEST WEB" > /var/www/html/index.html
EXPOSE 80
CMD ["/usr/sbin/apache2tl", "-DFOREGROUND"]
